version: '3.3'

services:
  wordpress:
    image: wordpressnode
    build: 
      context: .
      dockerfile: ./Docker/wordpressnode.Dockerfile
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - ./traefik/${ENVIRONMENT}.toml:/traefik.toml
      - ./traefik/ssl:/ssl
      - ./traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels: 
      - "traefik.frontend.rule=Host:${HOST};PathPrefixStrip:/router"
      - "traefik.frontend.auth.basic=sojuz:$$2y$$05$$dtSK0Lm6R0LrSKfMEYVGD.9tY/Od6R.f7TfJE2M6VIpQBK25xre3G"
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.passHostHeader=true"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.tags=traefiks"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      web:
    links: 
      - db
    depends_on:
      - db
    ports: 
      - 8888:80
    env_file: 
      - .env
    restart: unless-stopped
    labels:
      - "traefik.enable=false"