[api]
entryPoint = "traefik"
dashboard = true
debug = true

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
exposedByDefault = false
network = "web"

# Enable docker TLS connection.
#
# Optional
#
#  [docker.tls]
#  ca = "/etc/ssl/ca.crt"
#  cert = "/etc/ssl/docker.crt"
#  key = "/etc/ssl/docker.key"
#  insecureSkipVerify = true

defaultEntryPoints = ["https", "http", "traefik"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "ssl/cert.crt"
      keyFile = "ssl/cert.key"
  [entryPoints.traefik]
  address = ":8080"